# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
