# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20170728_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='postman_id',
            new_name='message_user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='wall_id',
        ),
        migrations.AddField(
            model_name='message',
            name='user_profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_prfile_messages', to='first_app.User'),
            preserve_default=False,
        ),
    ]
