# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20170728_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_messages', to='first_app.User'),
        ),
    ]
