# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20170728_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_id',
            new_name='comment_user_id',
        ),
    ]
